# Generated by Django 4.2.2 on 2023-09-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prague', '0002_alter_toilet_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toilet',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='Timeschedule',
        ),
        migrations.AddField(
            model_name='toilet',
            name='schedule',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
