# Generated by Django 4.2.2 on 2023-09-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prague', '0003_remove_toilet_schedule_delete_timeschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='schedule',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
